# 将静态内容部署到 GitHub Pages 的简易工作流程
name: fetch data.json

on:
  # 这个选项可以使你手动在 Action tab 页面触发工作流
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages。
permissions:
  contents: write
  # pages: write
  id-token: write

jobs:
  # 单次部署的工作描述
  fetch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: |
          npm install request
          npm install sqlite3
      - name: GetSQLiteFile
        run: node ./src/data/download.cjs
      - name: Run.js
        run: node ./src/data/readSQLite.cjs
      - name: Commit changes
        run: |
          git config --global user.email "prozhong@msn.cn"
          git config --global user.name "prozhong"
          git add ./src/data/data.json
          git commit -m "Auto commit at $(date)"
          git push
